name: CI/CI

on:
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests			
        run: yarn test --bail
    env:
      NEXT_PUBLIC_ENV:  ${{ secrets.NEXT_PUBLIC_ENV }}
      NEXT_PUBLIC_GITHUB_TOKEN:  ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID:  ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      NEXT_PUBLIC_SUPABASE_URL:  ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_KEY:  ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}

  chromatic-deployment:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to Chromatic			
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
