name: CI/CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Run tests			
        run: yarn test --bail
    env:
      NEXT_PUBLIC_ENV:  ${{ secrets.NEXT_PUBLIC_ENV }}
      NEXT_PUBLIC_GITHUB_TOKEN:  ${{ secrets.NEXT_PUBLIC_GITHUB_TOKEN }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID:  ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      NEXT_PUBLIC_SUPABASE_URL:  ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_KEY:  ${{ secrets.NEXT_PUBLIC_SUPABASE_KEY }}

  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install modules
        run: yarn --frozen-lockfile

      - name: Publish to Chromatic			
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
