name: Jest tests

on:
  pull_request:
    branches:
      - main
      - homolog

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test --bail
